# Generated by Django 2.0.3 on 2018-06-30 10:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='update',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 30, 10, 9, 54, 981915, tzinfo=utc), verbose_name='更新时间'),
        ),
    ]
