# Generated by Django 2.0.3 on 2018-04-03 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('describe', models.CharField(blank=True, max_length=200, null=True)),
                ('lookNumber', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('upDate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
