# Generated by Django 2.0.3 on 2018-04-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='upDate',
        ),
        migrations.AddField(
            model_name='topic',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
