# Generated by Django 2.0.3 on 2019-03-14 09:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181211_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='update',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 14, 9, 12, 17, 26734, tzinfo=utc), verbose_name='更新时间'),
        ),
    ]
