# Generated by Django 2.0.3 on 2018-05-07 16:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180403_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='标题')),
                ('article', models.TextField(blank=True, null=True, verbose_name='内容')),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='点击次数')),
                ('creatdate', models.DateTimeField(default=datetime.datetime(2018, 5, 7, 16, 1, 25, 703896, tzinfo=utc), verbose_name='创建时间')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
        ),
    ]
