# Generated by Django 2.0.3 on 2018-07-05 08:53

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180630_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCenterTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10, null=True, verbose_name='标题名称')),
                ('weight', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='1-100')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='标题的icon')),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='update',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 5, 8, 53, 54, 801187, tzinfo=utc), verbose_name='更新时间'),
        ),
    ]
