# Generated by Django 2.0.3 on 2019-03-20 08:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190314_0912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='topic',
        ),
        migrations.AddField(
            model_name='blog',
            name='classify',
            field=models.CharField(choices=[('iOS', 'iOS'), ('javascript', 'Javascript'), ('other', 'Other')], max_length=1, null=True, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='文章名字'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='update',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 20, 8, 26, 16, 177916, tzinfo=utc), verbose_name='更新时间'),
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
