# Generated by Django 2.0.3 on 2018-07-05 09:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180705_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercentertitle',
            name='isSuper',
            field=models.BooleanField(default=False, verbose_name='是否是超级用户所有'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='update',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 5, 9, 3, 42, 395595, tzinfo=utc), verbose_name='更新时间'),
        ),
    ]
