# Generated by Django 2.0.3 on 2018-05-10 12:13

import DjangoUeditor.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100)),
                ('Content', DjangoUeditor.models.UEditorField(blank=True, verbose_name='内容\t')),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='creatdate',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 10, 12, 13, 28, 283438, tzinfo=utc), verbose_name='创建时间'),
        ),
    ]
