# Generated by Django 2.0.3 on 2019-03-20 09:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190320_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='点击次数'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='update',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 20, 9, 31, 25, 958342, tzinfo=utc), verbose_name='更新时间'),
        ),
    ]
