# Generated by Django 2.0.3 on 2018-07-11 03:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180705_0903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videofile',
            name='name',
        ),
        migrations.AddField(
            model_name='videofile',
            name='fid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='update',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 11, 3, 56, 41, 431504, tzinfo=utc), verbose_name='更新时间'),
        ),
    ]
