# Generated by Django 2.0.3 on 2018-05-17 08:13

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180510_1213'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.AddField(
            model_name='blog',
            name='count',
            field=models.IntegerField(blank=True, null=True, verbose_name='点击次数'),
        ),
        migrations.AddField(
            model_name='blog',
            name='creatdate',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 17, 8, 13, 34, 668656, tzinfo=utc), verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='blog',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Topic'),
        ),
        migrations.AddField(
            model_name='blog',
            name='update',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
