# Generated by Django 2.0.3 on 2018-07-30 11:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180711_0356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='Content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='Name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='blog',
            name='update',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 30, 11, 57, 9, 14191, tzinfo=utc), verbose_name='更新时间'),
        ),
    ]
