# Generated by Django 2.0.3 on 2018-06-06 03:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180517_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='creatdate',
            field=models.DateTimeField(auto_now=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='update',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 6, 3, 13, 36, 804622, tzinfo=utc), verbose_name='更新时间'),
        ),
    ]
